2021-08-26 07:04:16,433 INFO    MainThread:22787 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 07:04:16,433 INFO    MainThread:22787 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 07:04:16,433 INFO    MainThread:22787 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_070416-3bbqxei3/logs/debug.log
2021-08-26 07:04:16,434 INFO    MainThread:22787 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_070416-3bbqxei3/logs/debug-internal.log
2021-08-26 07:04:16,434 INFO    MainThread:22787 [wandb_init.py:init():375] calling init triggers
2021-08-26 07:04:16,434 INFO    MainThread:22787 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-26 07:04:16,434 INFO    MainThread:22787 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 293va3ob
2021-08-26 07:04:16,436 INFO    MainThread:22787 [wandb_run.py:finish():1254] finishing run presto105/lv1_p/293va3ob
2021-08-26 07:04:16,474 INFO    MainThread:22787 [jupyter.py:save_history():339] not saving jupyter history
2021-08-26 07:04:16,474 INFO    MainThread:22787 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-26 07:04:16,474 INFO    MainThread:22787 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-26 07:04:16,474 INFO    MainThread:22787 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-26 07:04:16,474 INFO    MainThread:22787 [wandb_run.py:_restore():1526] restore
2021-08-26 07:04:17,382 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 1081
}

2021-08-26 07:04:17,638 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 1081
}

2021-08-26 07:04:17,779 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9778
}

2021-08-26 07:04:17,882 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9778
}

2021-08-26 07:04:17,985 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9778
}

2021-08-26 07:04:18,087 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9429
  total_bytes: 9778
}

2021-08-26 07:04:18,190 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 07:04:18,293 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 07:04:18,398 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 07:04:18,500 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 07:04:18,970 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 07:04:19,072 INFO    MainThread:22787 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 07:04:20,264 INFO    MainThread:22787 [wandb_run.py:_show_files():1898] logging synced files
2021-08-26 07:04:20,270 INFO    MainThread:22787 [wandb_init.py:init():424] starting backend
2021-08-26 07:04:20,270 INFO    MainThread:22787 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-26 07:04:20,273 INFO    MainThread:22787 [backend.py:ensure_launched():135] starting backend process...
2021-08-26 07:04:20,284 INFO    MainThread:22787 [backend.py:ensure_launched():139] started backend process with pid: 23008
2021-08-26 07:04:20,286 INFO    MainThread:22787 [wandb_init.py:init():429] backend started and connected
2021-08-26 07:04:20,303 INFO    MainThread:22787 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-26 07:04:20,303 INFO    MainThread:22787 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-26 07:04:20,304 INFO    MainThread:22787 [wandb_init.py:init():477] updated telemetry
2021-08-26 07:04:20,304 INFO    MainThread:22787 [wandb_init.py:init():500] communicating current version
2021-08-26 07:04:21,092 INFO    MainThread:22787 [wandb_init.py:init():505] got version response 
2021-08-26 07:04:21,092 INFO    MainThread:22787 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-26 07:04:21,312 INFO    MainThread:22787 [wandb_init.py:init():540] starting run threads in backend
2021-08-26 07:04:25,884 INFO    MainThread:22787 [wandb_run.py:_console_start():1584] atexit reg
2021-08-26 07:04:25,884 INFO    MainThread:22787 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-26 07:04:25,885 INFO    MainThread:22787 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-26 07:04:25,886 INFO    MainThread:22787 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-26 07:04:25,886 INFO    MainThread:22787 [wandb_init.py:init():565] run started, returning control to user process
2021-08-26 07:05:03,924 INFO    MainThread:22787 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 07:05:03,924 INFO    MainThread:22787 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 07:05:03,924 INFO    MainThread:22787 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_070503-3ujiakue/logs/debug.log
2021-08-26 07:05:03,924 INFO    MainThread:22787 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_070503-3ujiakue/logs/debug-internal.log
2021-08-26 07:05:03,925 INFO    MainThread:22787 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ff43e06a100>
2021-08-26 07:05:03,925 INFO    MainThread:22787 [wandb_init.py:init():375] calling init triggers
2021-08-26 07:05:03,926 INFO    MainThread:22787 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'epochs': 20, 'batch_size': 32, 'learning_rate': 0.001}
2021-08-26 07:05:03,926 INFO    MainThread:22787 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3bbqxei3
2021-08-26 07:05:03,928 INFO    MainThread:22787 [wandb_run.py:finish():1254] finishing run presto105/lv1_p/3bbqxei3
