2021-08-26 06:41:24,912 INFO    MainThread:17359 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 06:41:24,913 INFO    MainThread:17359 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 06:41:24,913 INFO    MainThread:17359 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '84f10b11a8fa0d0036151625c778049a02f3728b'}
2021-08-26 06:41:24,913 INFO    MainThread:17359 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_064124-zznditlp/logs/debug.log
2021-08-26 06:41:24,913 INFO    MainThread:17359 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_064124-zznditlp/logs/debug-internal.log
2021-08-26 06:41:24,913 INFO    MainThread:17359 [wandb_init.py:init():375] calling init triggers
2021-08-26 06:41:24,913 INFO    MainThread:17359 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'epochs': 3, 'batch_size': 32, 'learning_rate': 0.001}
2021-08-26 06:41:24,914 INFO    MainThread:17359 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3am5kidr
2021-08-26 06:41:24,915 INFO    MainThread:17359 [wandb_run.py:finish():1254] finishing run presto105/lv1_p/3am5kidr
2021-08-26 06:41:24,953 INFO    MainThread:17359 [jupyter.py:save_history():339] not saving jupyter history
2021-08-26 06:41:24,954 INFO    MainThread:17359 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-26 06:41:24,954 INFO    MainThread:17359 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-26 06:41:24,954 INFO    MainThread:17359 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-26 06:41:24,954 INFO    MainThread:17359 [wandb_run.py:_restore():1526] restore
2021-08-26 06:41:25,292 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 1081
}

2021-08-26 06:41:25,530 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 1081
}

2021-08-26 06:41:25,753 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9778
}

2021-08-26 06:41:25,857 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9778
}

2021-08-26 06:41:25,961 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9778
}

2021-08-26 06:41:26,064 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6584
  total_bytes: 9778
}

2021-08-26 06:41:26,167 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:26,271 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:26,373 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:26,475 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:26,577 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:26,985 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:27,087 INFO    MainThread:17359 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9778
  total_bytes: 9778
}

2021-08-26 06:41:28,279 INFO    MainThread:17359 [wandb_run.py:_show_files():1898] logging synced files
2021-08-26 06:41:28,283 INFO    MainThread:17359 [wandb_init.py:init():424] starting backend
2021-08-26 06:41:28,283 INFO    MainThread:17359 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-26 06:41:28,286 INFO    MainThread:17359 [backend.py:ensure_launched():135] starting backend process...
2021-08-26 06:41:28,314 INFO    MainThread:17359 [backend.py:ensure_launched():139] started backend process with pid: 17619
2021-08-26 06:41:28,315 INFO    MainThread:17359 [wandb_init.py:init():429] backend started and connected
2021-08-26 06:41:28,339 INFO    MainThread:17359 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-26 06:41:28,339 INFO    MainThread:17359 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-26 06:41:28,339 INFO    MainThread:17359 [wandb_init.py:init():477] updated telemetry
2021-08-26 06:41:28,340 INFO    MainThread:17359 [wandb_init.py:init():500] communicating current version
2021-08-26 06:41:29,136 INFO    MainThread:17359 [wandb_init.py:init():505] got version response 
2021-08-26 06:41:29,136 INFO    MainThread:17359 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-26 06:41:29,493 INFO    MainThread:17359 [wandb_init.py:init():540] starting run threads in backend
2021-08-26 06:41:34,021 INFO    MainThread:17359 [wandb_run.py:_console_start():1584] atexit reg
2021-08-26 06:41:34,022 INFO    MainThread:17359 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-26 06:41:34,022 INFO    MainThread:17359 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-26 06:41:34,023 INFO    MainThread:17359 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-26 06:41:34,023 INFO    MainThread:17359 [wandb_init.py:init():565] run started, returning control to user process
2021-08-26 06:41:47,585 INFO    MainThread:17359 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 06:41:47,586 INFO    MainThread:17359 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 06:41:47,586 INFO    MainThread:17359 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '84f10b11a8fa0d0036151625c778049a02f3728b'}
2021-08-26 06:41:47,587 INFO    MainThread:17359 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_064147-1cl17aep/logs/debug.log
2021-08-26 06:41:47,587 INFO    MainThread:17359 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_064147-1cl17aep/logs/debug-internal.log
2021-08-26 06:41:47,587 INFO    MainThread:17359 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6cd4b5ae50>
2021-08-26 06:41:47,588 INFO    MainThread:17359 [wandb_init.py:init():375] calling init triggers
2021-08-26 06:41:47,588 INFO    MainThread:17359 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'epochs': 3, 'batch_size': 32, 'learning_rate': 0.001}
2021-08-26 06:41:47,588 INFO    MainThread:17359 [wandb_init.py:init():395] re-initializing run, found existing run on stack: zznditlp
2021-08-26 06:41:47,590 INFO    MainThread:17359 [wandb_run.py:finish():1254] finishing run presto105/LV1.P/zznditlp
